/*
 * WHAT: Mapper class to convert between Lead entities and DTOs.
 * WHY:  We never expose database entities directly to the API, and we never
 *       save request DTOs directly to the database. The Mapper bridges the gap.
 * HOW:  Provides simple static-like methods (or Spring Beans) to map fields.
 */
package com.edgento.api.mapper;

import com.edgento.api.model.dto.request.CreateLeadRequest;
import com.edgento.api.model.dto.response.LeadResponse;
import com.edgento.api.model.entity.Lead;
import org.springframework.stereotype.Component;

@Component
public class LeadMapper {

    // Converts the incoming Request Record into a database Entity
    public Lead toEntity(CreateLeadRequest request) {
        if (request == null) {
            return null;
        }

        Lead lead = new Lead();
        lead.setName(request.name());
        lead.setEmail(request.email());
        lead.setCompanyName(request.companyName());
        lead.setPhone(request.phone());
        lead.setSourcePage(request.sourcePage());
        lead.setUtmSource(request.utmSource());
        // ID and createdAt will be auto-generated by the database/JPA
        return lead;
    }

    // Converts the database Entity into an outgoing Response Record
    public LeadResponse toResponse(Lead entity) {
        if (entity == null) {
            return null;
        }

        return new LeadResponse(
                entity.getId(),
                entity.getName(),
                entity.getEmail(),
                entity.getCompanyName(),
                entity.getCreatedAt()
        );
    }
}
